version: "3"

services:
  serviio:
    image: jpspringall/serviio:latest
    container_name: serviio
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=TZ/CODE
    volumes:
      - /tmp:/tmp
      - /etc/localtime:/etc/localtime
      - /data/image:/media/image
      - /data/audio:/media/audio
      - /data/video:/media/video
      - serviio_library:/opt/serviio/library
      - serviio_log:/opt/serviio/log
      - serviio_plugins:/opt/serviio/plugins
    ports:
      - "23423:23423/tcp"
      - "8895:8895/tcp"
      - "1900:1900/udp"
    restart: always

volumes:
  serviio_library:
    external: true
  serviio_log:
    external: true
  serviio_plugins:
    external: true

#networks:
#  host:
#    external: true
